async function only(nyz, rimurubotz, from) {  
if (nyz == "isGroup") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/onlygroup.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] GUNAKAN DI GROUP!"}}  })}
if (nyz == "isGroupAdmins") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/onlyadmin.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] KAMU BUKAN ADMIN!"}}  })}
if (nyz == "isOwner") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/onlyowner.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] KAMU BUKAN OWNER!"}}  })}
if (nyz == "isBotGroupAdmins") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/botadmin.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] BOT BUKAN ADMIN!"}}  })}
if (nyz == "error") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/error.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] COBA LAGI NANTI!"}}  })}
if (nyz == "sukses") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/sukses.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] STATUS SUKSES!"}}  })}
if (nyz == "proses") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/proses.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] TUNGGU SEBENTAR!"}}  })}
if (nyz == "antilink") { rimurubotz.sendMessage(from, {sticker:{url:"https://raw.githubusercontent.com/naylachan/STICKER/main/antilink.webp"}},{quoted:{ key: {fromMe: false, participant: `0@s.whatsapp.net`, ...(from ? { remoteJid: "status@broadcast" } : {})},message: {"conversation": "[ *INFO* ] LINK DETEKSI!"}}  })}
} 
module.exports = { only }